version: '3.7'

services:
  s3:
    image: localstack/localstack:2.1.0
    container_name: s3-localstack
    hostname: s3-localstack
    networks:
      - localstack-network
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1

networks:
  localstack-network:
    external: false
    driver: bridge
    name: localstack-network